/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.speedruncrud;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author krizk
 */
public class FORM extends javax.swing.JFrame {

    /**
     * Creates new form FORM
     */
    public FORM() {
        initComponents();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        optionpane = new javax.swing.JOptionPane();
        jLabel1 = new javax.swing.JLabel();
        NIS = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        NAMA = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        JURUSAN = new javax.swing.JComboBox<>();
        KELAS = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("APLIKASI PENDATAAN SISWA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 24, -1, -1));

        NIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NISActionPerformed(evt);
            }
        });
        getContentPane().add(NIS, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 150, 30));

        jLabel2.setText("JURUSAN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 50, -1));

        NAMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAMAActionPerformed(evt);
            }
        });
        getContentPane().add(NAMA, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 150, 30));

        jLabel3.setText("NAMA");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 50, -1));

        JURUSAN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RPL", "MM", "AKL", "PKM", "BDP" }));
        getContentPane().add(JURUSAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 140, 30));

        KELAS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "11", "12" }));
        KELAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KELASActionPerformed(evt);
            }
        });
        getContentPane().add(KELAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 140, 30));

        jLabel4.setText("NIS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 50, -1));

        jLabel5.setText("KELAS");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, 50, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 357, 990, 290));

        jButton1.setText("TAMBAH DATA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));

        jButton2.setText("UPDATE DATA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, -1));

        jButton3.setText("HAPUS DATA");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, -1, -1));

        pack();
    }// </editor-fold>                        

    private void NISActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
    }                                   
    private void loadTable() {
        try {
            DefaultTableModel model = new DefaultTableModel();
            int no = 1;
            model.addColumn("NO");
            model.addColumn("NIS");
            model.addColumn("NAMA");
            model.addColumn("KELAS");
            model.addColumn("JURUSAN");
            Connection con = koneksi.configDB();
            Statement stmt = con.createStatement();
            ResultSet res = stmt.executeQuery("select * from tb_siswa");
            while(res.next()) {
            model.addRow(new Object[]{no++, res.getString(1), res.getString(2), res.getString(3), res.getString(4)});
            }
            jTable1.setModel(model);
        } catch(Exception e) {
        
        }
    
    }
    private void NAMAActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void KELASActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        try {
            Connection con = koneksi.configDB();
            PreparedStatement pst 
                    = con.prepareStatement("insert into tb_siswa(nis, nama, kelas, jurusan) values('"+NIS.getText()+"', '"+NAMA.getText()+"', '"+KELAS.getSelectedItem()+"', '"+JURUSAN.getSelectedItem()+"')");
            pst.execute();
            loadTable();
            clearInput();
            optionpane.showMessageDialog(null, "Data Berhasil DiTambah");

        } catch(Exception e) {
            optionpane.showMessageDialog(null, "Data Tidak Berhasil DiTambah");

        }
    }                                        
    private void clearInput(){
        NAMA.setText("");
        NIS.setText("");
        KELAS.setSelectedIndex(0);
        JURUSAN.setSelectedIndex(0);
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        try {
           Connection con = koneksi.configDB();
            PreparedStatement pst 
                    = con.prepareStatement("update tb_siswa set nis = '"+NIS.getText()+"', nama = '"+NAMA.getText()+"', kelas = '"+KELAS.getSelectedItem()+"', jurusan= '"+JURUSAN.getSelectedItem()+"' WHERE nis='"+NIS.getText()+"'");
            pst.execute();
            loadTable();
            clearInput();
            optionpane.showMessageDialog(null, "Data Berhasil DiUpdate");

        }catch(Exception e) {
             optionpane.showMessageDialog(null, "Data Tidak Berhasil DiUpdate");

        }
    }                                        

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {                                     
        int row = jTable1.rowAtPoint(evt.getPoint());
        String Nis, Nama, Jurusan, Kelas;
        Nis = jTable1.getValueAt(row, 1).toString();
        Nama = jTable1.getValueAt(row, 2).toString();
        Jurusan = jTable1.getValueAt(row, 3).toString();
        Kelas = jTable1.getValueAt(row, 4).toString();
        NIS.setText(Nis);
        NAMA.setText(Nama);
        JURUSAN.setSelectedItem(Jurusan);
        KELAS.setSelectedItem(Kelas);
    }                                    

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        try {
        Connection con = koneksi.configDB();
            PreparedStatement pst 
                    = con.prepareStatement("DELETE FROM tb_siswa WHERE nis='"+NIS.getText()+"'");
            pst.execute();
            loadTable();
            clearInput();
            optionpane.showMessageDialog(null, "Data Berhasil Dihapus");
        } catch(Exception e) {
            optionpane.showMessageDialog(null, "Data Gagal Dihapus");

        }
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FORM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JComboBox<String> JURUSAN;
    private javax.swing.JComboBox<String> KELAS;
    private javax.swing.JTextField NAMA;
    private javax.swing.JTextField NIS;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JOptionPane optionpane;
    // End of variables declaration                   
}
